class VirDumbo:HDWeapon{
	default{
		//$Category "Weapons/Hideous Destructor"
		//$Title "Grenade Launcher"
		//$Sprite "BLOPA0"

		+weapon.explosive
		+hdweapon.fitsinbackpack
		weapon.selectionorder 94;
		weapon.slotnumber 5;
		weapon.slotpriority 3;
		scale 0.6;
		inventory.pickupmessage "$PICKUP_DUMBO";
		obituary "$OB_DUMBO";
		hdweapon.barrelsize 27,1.6,3;
		tag "$TAG_DUMBO";
		hdweapon.refid "dmb";

		hdweapon.ammo1 "WAN_20mmGrenadeAmmo",2;
	}
	override bool AddSpareWeapon(actor newowner){return AddSpareWeaponRegular(newowner);}
	override hdweapon GetSpareWeapon(actor newowner,bool reverse,bool doselect){return GetSpareWeaponRegular(newowner,reverse,doselect);}
	override double gunmass(){
		return weaponstatus[0]&DUMBO_LOADED?5:4;
	}
	override double weaponbulk(){
		return 65+(weaponstatus[0]&DUMBO_LOADED?ENC_20MMGRENADELOADED:0);
	}
	override string,double getpickupsprite(){return "DMBOX0",1.;}
	override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
		if(sb.hudlevel==1){
			sb.drawimage("MA7GB0",(-52,-4),sb.DI_SCREEN_CENTER_BOTTOM,scale:(0.6,0.6));
			sb.drawnum(hpl.countinv("WAN_20mmGrenadeAmmo"),-45,-8,sb.DI_SCREEN_CENTER_BOTTOM);
		}
		if(hdw.weaponstatus[0]&DUMBO_LOADED)sb.drawrect(-21,-13,5,3);
		int ab=hdw.airburst;
		sb.drawstring(
			sb.mAmountFont,ab?string.format("%.2f",hdw.airburst*0.01):"--.--",
			(-28,-15),sb.DI_SCREEN_CENTER_BOTTOM|sb.DI_TEXT_ALIGN_RIGHT,
			ab?Font.CR_WHITE:Font.CR_BLACK
		);
		sb.drawwepnum(
			hpl.countinv("WAN_20mmGrenadeAmmo"),
			(HDCONST_MAXPOCKETSPACE/ENC_ROCKET)
		);
		sb.drawrect(-28,-43+min(32,ab>>8),6,1);
		sb.drawrect(-23,-42,1,32);
		sb.drawrect(-25,-42,1,32);
	}
	override string gethelptext(){
		LocalizeHelp();
		return
		LWPHELP_FIRESHOOT
		..LWPHELP_ALTFIRE..StringTable.Localize("$BLOPWH_ALTFIRE")
		..LWPHELP_RELOADRELOAD
		..LWPHELP_FIREMODE.."+"..LWPHELP_UPDOWN..StringTable.Localize("$BLOPWH_AIRBURST")
		..LWPHELP_UNLOADUNLOAD
		;
	}
	override void DrawSightPicture(
		HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl,
		bool sightbob,vector2 bob,double fov,bool scopeview,actor hpc
	){
		int cx,cy,cw,ch;
        [cx,cy,cw,ch]=screen.GetClipRect();
        vector2 scc;
        vector2 bobb=bob*1.3;
        
        sb.SetClipRect(
			-15+bob.x,-16+bob.y,27,40,
				sb.DI_SCREEN_CENTER
			);
			scc=(0.75,0.75);
 
        sb.drawimage(
            "DMBOFRNT",(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
            scale:scc
        );
        sb.SetClipRect(cx,cy,cw,ch);
        sb.drawimage(
            "DMBOBACK",(0,10)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
            alpha:0.9,
            scale:scc
        );
//		sb.drawgrenadeladder(hdw.airburst,bob);
	}
	override void DropOneAmmo(int amt){
		if(owner){
			amt=clamp(amt,1,10);
			owner.A_DropInventory("WAN_20mmGrenadeAmmo",1);
		}
	}
	override void ForceBasicAmmo(){
		owner.A_SetInventory("WAN_20mmGrenadeAmmo",1);
	}
	
	action void A_Fire20mmGL(string firingsound="weapons/grenadeshot"){
		A_StartSound(firingsound,CHAN_WEAPON,CHANF_OVERLAP);
		vector3 gpos=pos+gunpos((0,0,-getdefaultbytype("WAN_20mmgrenade").height*0.6));
		let ggg=WAN_20mmgrenade(spawn("WAN_20mmgrenade",gpos,ALLOW_REPLACE));

		ggg.speed*=1.45;

		let hdp=hdplayerpawn(self);
		if(hdp){
			ggg.angle=hdp.gunangle;
			ggg.pitch=hdp.gunpitch-2.5;
		}else{
			ggg.angle=angle;
			ggg.pitch=pitch-2.5;
		}

		ggg.target=self;ggg.master=self;
		ggg.primed=false;
		if(invoker.airburst){
			ggg.airburst=max(1000,invoker.airburst)*HDCONST_ONEMETRE*0.01;
			if(!player||!(player.cmd.buttons&BT_ZOOM))invoker.airburst=0;
		}
	}
	
	states{
	select0:
		DMBO A 0;
		goto select0small;
	deselect0:
		DMBO A 0;
		goto deselect0small;

	ready:
		DMBO A 1 A_WeaponReady(WRF_ALL);
		goto readyend;
	hold:
	altfire:
		DMBO A 0{invoker.airburst=0;}
		goto nope;
	firemode:
		goto abadjust;

	fire:
		DMBO A 0 A_JumpIf(invoker.weaponstatus[0]&DUMBO_LOADED,"reallyshoot");
		goto nope;
	reallyshoot:
		DMBO A 1{
			A_Fire20mmGL(firingsound:"weapons/dumbo");
			invoker.weaponstatus[0]&=~DUMBO_LOADED;
		}
		DMBO A 1 offset(0,34);
		DMBO A 0{
			A_ZoomRecoil(0.9);
			A_MuzzleClimb(-frandom(2.,2.7),-frandom(3.4,5.2));
		}
		goto nope;
	loadcommon:
		DMBO A 1 offset(2,34);
		DMBO A 1 offset(4,38)A_MuzzleClimb(-frandom(1.2,2.4),frandom(1.2,2.4),wepdot:false);
		DMBO A 1 offset(10,44);
		DMBO A 2 offset(12,50)A_MuzzleClimb(-frandom(1.2,2.4),frandom(1.2,2.4),wepdot:false);
		DMBO B 3 offset(13,55)A_StartSound("weapons/bloopopen",8);
		DMBO B 3 offset(14,60) A_StartSound("weapons/bloopopen2",8,CHANF_OVERLAP);
		DMBO B 3 offset(11,64)A_StartSound("weapons/pocket",9);
		DMBO B 7 offset(10,66);
		DMBO B 0{
			if(health<40)A_SetTics(7);
			else if(health<60)A_SetTics(3);
		}
		DMBO B 4 offset(12,68) A_StartSound("weapons/bloopreload",8);
		DMBO B 2 offset(10,66){
			if(invoker.weaponstatus[0]&DUMBO_JUSTUNLOAD){
				if(
					!(invoker.weaponstatus[0]&DUMBO_LOADED)
				)setweaponstate("reloadend");else{
					invoker.weaponstatus[0]&=~DUMBO_LOADED;
					if(
						(!PressingUnload()&&!PressingReload())
						||A_JumpIfInventory("WAN_20mmGrenadeAmmo",0,"null")
					)
					A_SpawnItemEx(
						"WAN_20mmGrenadeAmmo",10,0,height-16,vel.x,vel.y,vel.z+2,
						0,SXF_ABSOLUTEMOMENTUM|SXF_NOCHECKPOSITION
					);
					else{
						A_GiveInventory("WAN_20mmGrenadeAmmo",1);
						A_StartSound("weapons/pocket",9);
						A_SetTics(4);
					}
				}
			}else{
				if(
					invoker.weaponstatus[0]&DUMBO_LOADED
					||!countinv("WAN_20mmGrenadeAmmo")
				)setweaponstate("reloadend");else{
					A_TakeInventory("WAN_20mmGrenadeAmmo",1,TIF_NOTAKEINFINITE);
					invoker.weaponstatus[0]|=DUMBO_LOADED;
					A_SetTics(5);
				}
			}
		}
	reloadend:
		DMBO A 1 offset(12,68) A_StartSound("weapons/bloopopen2",8);
		DMBO A 1 offset(11,70);
		DMBO A 4 offset(10,69);
		DMBO A 0 A_StartSound("weapons/bloopopen",8,CHANF_OVERLAP);
		DMBO A 1 offset(9,66);
		DMBO A 1 offset(9,60);
		DMBO A 1 offset(8,53);
		DMBO A 1 offset(8,48);
		DMBO A 1 offset(6,43);
		DMBO A 1 offset(4,38);
		DMBO A 1 offset(2,34);
		goto ready;
	altreload:
	reload:
		DMBO A 0 A_JumpIf(
			invoker.weaponstatus[0]&DUMBO_LOADED
			||!countinv("WAN_20mmGrenadeAmmo"),
			"nope"
		);
		DMBO A 0{
			if(
				invoker.weaponstatus[0]&DUMBO_LOADED
				||!countinv("WAN_20mmGrenadeAmmo")
			)setweaponstate("nope");else{
				invoker.weaponstatus[0]&=~DUMBO_JUSTUNLOAD;
			}
		}goto loadcommon;
	unload:
		DMBO A 0{
			if(
				!(invoker.weaponstatus[0]&DUMBO_LOADED)
			)setweaponstate("nope");else{
				invoker.weaponstatus[0]|=DUMBO_JUSTUNLOAD;
			}
		}goto loadcommon;

	spawn:
		DMBO X -1;
	}
	override void loadoutconfigure(string input){
		//there isn't actually anything to configure,
		//but we need this to keep it loaded
		weaponstatus[0]|=DUMBO_LOADED;
	}
	override void InitializeWepStats(bool idfa){
		weaponstatus[0]|=DUMBO_LOADED;
		if(!idfa && !owner){
			airburst=0;
		}
	}
}

enum dumbostatus{
	DUMBO_LOADED=1,
	DUMBO_JUSTUNLOAD=2,

	DUMB_STATUS=0,
	DUMB_AIRBURST=1,
};

class DumboDrop : IdleDummy{
	states{
	spawn:
		TNT1 A 0 nodelay{
			spawn("VirDumbo",pos+(2,0,0),ALLOW_REPLACE);
			spawn("WAN_20mmGrenadeBox",pos+(7,0,0),ALLOW_REPLACE);
			}
			stop;
	}
}