// ------------------------------------------------------------
// Just a Longbow.
// Barely Functional. It's more of a proof-of-concept right now.	
//
//	There is also plans for a quiver, but i'll probably need help with that. 
//	I'm bad with anything relating to backpack items.	--- Slogstin
// ------------------------------------------------------------
class VirLongbow:HDWeapon{
	default{
		weapon.selectionorder 31;
		weapon.slotnumber 3;
		weapon.slotpriority 1;
		weapon.bobrangex 0.21;
		weapon.bobrangey 0.9;
		scale 0.7;
		inventory.pickupmessage "$PICKUP_VIRIDBOW";
		hdweapon.barrelsize 10,0.5,2;
		hdweapon.refid "VLB";
		tag "$TAG_VIRIDBOW";
		obituary "$OB_VIRIDBOW";
		inventory.icon "VBOWA0";
	}
	
	override bool AddSpareWeapon(actor newowner){return AddSpareWeaponRegular(newowner);}
	override hdweapon GetSpareWeapon(actor newowner,bool reverse,bool doselect){return GetSpareWeaponRegular(newowner,reverse,doselect);}
	
	override double weaponbulk(){
		return 70;
	}
	override double gunmass(){
		return 9;
	}
	
	override string gethelptext(){
		return
		WEPHELP_FIRE.."  Draw String\n"
		..WEPHELP_ALTFIRE.."   Withdraw\n"
		..WEPHELP_RELOAD.."   Load Arrow (Quiver first)\n"
//		..WEPHELP_FIREMODE.."	Thrust attack\n"
		..WEPHELP_ALTRELOAD.."	Load Quiver\n"
		..WEPHELP_UNLOAD.."   Unload Arrow\n"
		;
	}
	
	override string,double getpickupsprite(){return "VBOWA0",1.;}
	
	override void ForceBasicAmmo(){
		owner.A_TakeInventory("VirArrowAmmo");
		owner.A_GiveInventory("VirArrowAmmo");
//		ForceOneBasicAmmo("HDTommyDrum");
	}
	
	states{
	
	// ----- SELECT -----
	
	select0:
		VLBE A 0 A_JumpIf(invoker.weaponstatus[VBOW_LOADED]==0,4);
		VLBL A 0 ;
		#### # 0;
		goto select0big;
	deselect0:
		VLBE A 0 A_JumpIf(invoker.weaponstatus[VBOW_LOADED]==0,4);
		VLBL A 0 ;
		VLBL A 3;
		VLBE A 3;
		#### # 0;
		goto deselect0big;
	ready:
		#### # 1;
		#### # 0 A_JumpIf(pressingreload(),"reload");
		#### # 0 A_WeaponReady();
		goto readyend;
		
	// ----- RELOAD -----
	
	reload:
		#### # 0 A_JumpIf(invoker.weaponstatus[VBOW_LOADED]==1,"nope");
		#### # 0 A_JumpIf(!countinv("VirArrowAmmo"),"nope");
	loadarrow:
		#### # 1 offset(0,34) A_StartSound("bow/arrowslide",9);
		#### # 1 offset(2,36);
		#### # 1 offset(2,44);
		#### # 1 offset(5,58);
		#### # 2 offset(7,70);
		#### # 3 offset(8,80);
		#### # 4 offset(8,87){
			if(countinv("VirArrowAmmo")){
				A_TakeInventory("VirArrowAmmo",1,TIF_NOTAKEINFINITE);
				invoker.weaponstatus[VBOW_LOADED]=1;
			}
		}
		VLBL A 3 offset(9,76);
		#### # 2 offset(5,70);
		#### # 1 offset(5,64);
		#### # 1 offset(5,52);
		#### # 1 offset(5,42);
		#### # 1 offset(2,36);
		#### # 2 offset(0,34);
		goto nope;
		
	// ----- FIRE -----
		
	fire:
	draw0:
		#### A 3 offset(0,33);
		#### # 0 A_JumpIf(!pressingfire(),"shoot");
		#### A 4 offset(0,32);
	draw1:
		#### # 0 {
			invoker.weaponstatus[VBOW_DRAW]++;
		}
		#### # 0 A_StartSound("bow/pullalt",CHAN_WEAPON);
		#### B 3 offset(0,31);
		#### # 0 A_JumpIf(!pressingfire(),"shoot");
		#### B 4 offset(0,30);
	draw2:
		#### # 0 {
			invoker.weaponstatus[VBOW_DRAW]++;
		}
		#### C 3 offset(0,29);
		#### # 0 A_JumpIf(!pressingfire(),"shoot");
		#### C 4 offset(0,28);
	draw3:
		#### # 0 {
			invoker.weaponstatus[VBOW_DRAW]++;
		}
		#### D 3 offset(0,27);
		#### # 0 A_JumpIf(!pressingfire(),"shoot");
		#### D 4 offset(0,26);
	drawhold:
		#### # 0 {
			invoker.weaponstatus[VBOW_DRAW]++;
		}
		VLBE D 0 A_JumpIf(invoker.weaponstatus[VBOW_LOADED]==0,2);
		VLBL D 0 ;
		#### D 0 {
					if(hdplayerpawn(self) && random(0,100) < 15)hdplayerpawn(self).fatigue+=1;
		}
		#### D 0 {
					if(hdplayerpawn(self).fatigue>=35){
						hdplayerpawn(self).stunned+=35;
						setweaponstate("shoot");
						A_StartSound(painsound,CHAN_VOICE);
					}
				}
		#### D 1 A_JumpIf(pressingaltfire(),"withdraw");
		TNT1 A 0 A_ReFire("drawhold");
	shoot:
		#### # 0 A_JumpIf(invoker.weaponstatus[VBOW_LOADED]==0,"boing");
		#### # 0 A_JumpIf(invoker.weaponstatus[VBOW_DRAW]==0,"flash0");
		#### # 0 A_JumpIf(invoker.weaponstatus[VBOW_DRAW]==1,"flash1");
		#### # 0 A_JumpIf(invoker.weaponstatus[VBOW_DRAW]==2,"flash2");
		#### # 0 A_JumpIf(invoker.weaponstatus[VBOW_DRAW]==3,"flash3");
	flashfull:
		#### # 0 A_StartSound("bow/shoot",CHAN_WEAPON);
		VLBL DA 1 {
			        let bbb=HDBulletActor.FireBullet(self,"VirB_ARROW",spread:1.,speedfactor:frandom(1,1.1));
					invoker.weaponstatus[VBOW_LOADED]=0;
					invoker.weaponstatus[VBOW_DRAW]=0;
		}
		VLBE A 0;
		goto nope;
	flash3:
		#### # 0 A_StartSound("bow/shoot",CHAN_WEAPON);
		VLBL DA 1 {
			        let bbb=HDBulletActor.FireBullet(self,"VirB_ARROW",spread:1.,speedfactor:frandom(0.75,0.8));
					invoker.weaponstatus[VBOW_LOADED]=0;
					invoker.weaponstatus[VBOW_DRAW]=0;
		}
		VLBE A 0;
		goto nope;
	flash2:
		#### # 0 A_StartSound("bow/shoot",CHAN_WEAPON);
		VLBL DA 1 {
			        let bbb=HDBulletActor.FireBullet(self,"VirB_ARROW",spread:1.,speedfactor:frandom(0.45,0.5));
					invoker.weaponstatus[VBOW_LOADED]=0;
					invoker.weaponstatus[VBOW_DRAW]=0;
		}
		VLBE A 0;
		goto nope;
	flash1:
		#### # 0 A_StartSound("bow/shoot",CHAN_WEAPON);
		VLBL DA 1 {
			        let bbb=HDBulletActor.FireBullet(self,"VirB_ARROW",spread:1.,speedfactor:frandom(0.25,0.3));
					invoker.weaponstatus[VBOW_LOADED]=0;
					invoker.weaponstatus[VBOW_DRAW]=0;
		}
		VLBE A 0;
		goto nope;
	flash0:
		#### # 0 A_StartSound("bow/shoot",CHAN_WEAPON);
		VLBL DA 1 {
			        let bbb=HDBulletActor.FireBullet(self,"VirB_ARROW",spread:1.,speedfactor:frandom(0.08,0.13));
					invoker.weaponstatus[VBOW_LOADED]=0;
					invoker.weaponstatus[VBOW_DRAW]=0;
		}
		VLBE A 0;
		goto nope;
	boing:
		VLBE DA 1;
		goto nope;
		
	withdraw:
		#### # 0 A_StartSound("bow/withdraw",CHAN_WEAPON);
		#### DCBA 2 ;
		goto nope;
		
	// ----- SPAWN -----
	
	spawn:
		VBOW A -1;
		stop;
	}
}

enum vlongbowstatus{
	VBOW_LOADED=1,
	VBOW_IGNITED=2,
	VBOW_QUIVER=3,
	VBOW_DRAW=4,
};