// ------------------------------------------------------------
// 	A reworked MP40, featuring a stock that can be folded or extended
//	at will.
//	Extending it will yield much better control over the gun, at the cost
//	of a bulkier weapon.	--- Slogstin
// ------------------------------------------------------------

const ENC_MP40_BOX_EMPTY = 9;

const ENC_MP40_BOX_LOADED = ENC_MP40_BOX_EMPTY*0.7;


//based off Juan Horseshoe Pistol code

class VirMP40 :HDWeapon{
    //flags used for managing reloads
    //bool MAG_BOX;
    //bool MAG_DRUM;
    bool MAG_FORCEBOX;
    bool MAG_FORCEDRUM;
    
	default{
		+hdweapon.fitsinbackpack
		scale 0.53;
		weapon.selectionorder 50;
		weapon.slotnumber 3;
		weapon.slotpriority 3;
		weapon.kickback 55;
		weapon.bobrangex 0.77;
		weapon.bobrangey 0.99;
		weapon.bobspeed 2.15;
		weapon.bobstyle "normal";
		inventory.pickupmessage "You got the MP40. Keep moving like lightning!";
		obituary "%o got Blitzkrieg'd.";
		tag "MP40";
		hdweapon.refid "MP4";
		hdweapon.barrelsize 25,0.3,0.4;
		inventory.icon "MP4PB0";
	}

	override void postbeginplay(){
		super.postbeginplay();
		weaponspecial=1337;//UaS stabilizer compatibility
	}


	//Took the stock code from Poteto's Mac11	--- Slogstin
	action void A_StockExtend(){
	invoker.barrellength = 33.5;
	invoker.bobspeed = 1.8;
	invoker.bobrangey = 0.35;
	invoker.bobrangex = 0.1;
	invoker.kickback = 28;
	A_StartSound("weapons/MACStockOut",CHAN_6);
	invoker.weaponstatus[MP40D_STOCK]=1;
	}
	action void A_StockRetract(){
	invoker.barrellength = 25.0;
	invoker.bobspeed = 2.15;
	invoker.bobrangey = 0.99;
	invoker.bobrangex = 0.77;
	invoker.kickback = 55;
		A_StartSound("weapons/MACStockIn",CHAN_6);
		invoker.weaponstatus[MP40D_STOCK]=0;
	}

	override double gunmass(){return 10;}
	override double weaponbulk(){return 110;}
	
	override void failedpickupunload(){
	  failedpickupunloadmag(MP40S_MAG,"VirMP40Mag");
	}
	
	override string,double getpickupsprite(bool usespare)
    { string sprind;
      string sprname="MP4P";

			// For ammo reloads via cheats. 
			if (weaponstatus[MP40D_STOCK] > 0){
				sprind = (weaponstatus[MP40S_MAG] < 0) ? "C" : "D";} // C = no mag, A = mag
			else{ // stock in
				sprind = (weaponstatus[MP40S_MAG] < 0) ? "A" : "B";} // D = no mag, B = mag

      return sprname..sprind.."0",1.;
    }

	override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
		if(sb.hudlevel==1){
		
			int nextpmagloaded=sb.GetNextLoadMag(hdmagammo(hpl.findinventory("VirMP40Mag")));
			if(nextpmagloaded>=32){
				sb.drawimage("MP4MA0",(-63,-3),sb.DI_SCREEN_CENTER_BOTTOM,scale:(1,1));
			}else if(nextpmagloaded<1){
				sb.drawimage("MP4MC0",(-63,-3),sb.DI_SCREEN_CENTER_BOTTOM,alpha:nextpmagloaded?0.6:1.,scale:(1,1));
			}else sb.drawbar(
				"MP4MA0","MP4MC0",
				nextpmagloaded,32,
				(-63,-3),-1,
				sb.SHADER_VERT,sb.DI_SCREEN_CENTER_BOTTOM
			);
    
    //spare mag counters
	    sb.drawnum(hpl.countinv("VirMP40Mag"),-56,-8,sb.DI_SCREEN_CENTER_BOTTOM);
		}
		
		//main ammobar
		sb.drawwepnum(hdw.weaponstatus[MP40S_MAG],
		              hdw.weaponstatus[MP40S_MAG]>32?
		                hdw.weaponstatus[MP40S_MAG]:32,-16);
		
		
		//chamber status
		if(hdw.weaponstatus[MP40S_CHAMBER]==2)sb.drawrect(-19,-11,3,1);
		if(hdw.weaponstatus[MP40S_CHAMBER]==1)sb.drawrect(-17,-11,1,1);
		
		// HUD element to show if the stock is out or not.
		// Chose to do it this way, cause the gun sprite would make it difficult to show	--- Slogstin		
		if (hdw.weaponstatus[MP40D_STOCK]>0){sb.drawrect(-45,-11,15,1);
											sb.drawrect(-45,-11,1,3);
											sb.drawrect(-46,-13,1,2);
											}
	}
	
	override string gethelptext(){
		return
		WEPHELP_FIRESHOOT
		..WEPHELP_ALTFIRE.."  Rack bolt\n"
		..WEPHELP_RELOAD.."  Reload\n"
		..WEPHELP_FIREMODE.."  Extend/Retract stock\n"
		..WEPHELP_UNLOADUNLOAD
		..WEPHELP_MAGMANAGER
		;
	}
	
	override void DrawSightPicture(
		HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl,
		bool sightbob,vector2 bob,double fov,bool scopeview,actor hpc
	){
		int cx,cy,cw,ch;
		[cx,cy,cw,ch]=screen.GetClipRect();
		vector2 scc;
		vector2 bobb=bob*1.3;
			
		sb.SetClipRect(
			-8+bob.x,-9+bob.y,17,19,
			sb.DI_SCREEN_CENTER
		);
		scc=(0.6,0.6);
		
		//front sight
		sb.drawimage(
			"mp40fsit",(0,-5)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
			scale:scc
		);

    //rear sight
		sb.SetClipRect(cx,cy,cw,ch);
		sb.drawimage(
			"mp40bsit",(0,-3)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
			alpha:1,
			scale:scc
		);
	}
	
	override void DropOneAmmo(int amt){
		if(owner){
			amt=clamp(amt,1,10);
			if(owner.countinv("HDPistolAmmo"))
			  owner.A_DropInventory("HDPistolAmmo",amt*32);
		  else if(owner.countinv("VirMP40Mag"))
		    owner.A_DropInventory("VirMP40Mag",amt);
		}
	}
	
	override void ForceBasicAmmo(){
		owner.A_TakeInventory("HDPistolAmmo");
		ForceOneBasicAmmo("VirMP40Mag");
	}
	
	states{
	select0:
		MP40 E 0 A_JumpIf(!invoker.weaponstatus[MP40S_COCKED]
			                &&invoker.weaponstatus[MP40S_MAG]>=0,4);//Mag, uncocked
		#### D 0 A_JumpIf(!invoker.weaponstatus[MP40S_COCKED]
					            &&invoker.weaponstatus[MP40S_MAG]<0,3);//no mag, uncocked
		#### B 0 A_JumpIf(invoker.weaponstatus[MP40S_MAG]>=0,2);//Mag, cocked
		#### A 0;//no Mag, cocked
		#### # 0;
		#### # 0 {If(invoker.weaponstatus[MP40S_COCKED]>0)setweaponstate("select0bfg");}
		goto select0big;
	deselect0:
		MP40 E 0 A_JumpIf(!invoker.weaponstatus[MP40S_COCKED]
			                &&invoker.weaponstatus[MP40S_MAG]>=0,4);//Mag, uncocked
		#### D 0 A_JumpIf(!invoker.weaponstatus[MP40S_COCKED]
					            &&invoker.weaponstatus[MP40S_MAG]<0,3);//no mag, uncocked
		#### B 0 A_JumpIf(invoker.weaponstatus[MP40S_MAG]>=0,2);//Mag, cocked
		#### A 0;//no Mag, cocked
		#### # 0;
		#### # 0 {If(invoker.weaponstatus[MP40S_COCKED]>0)setweaponstate("deselect0bfg");}
		goto deselect0big;

	ready:
		MP40 E 0 A_JumpIf(!invoker.weaponstatus[MP40S_COCKED]
			                &&invoker.weaponstatus[MP40S_MAG]>=0,4);//Mag, uncocked
		#### D 0 A_JumpIf(!invoker.weaponstatus[MP40S_COCKED]
					            &&invoker.weaponstatus[MP40S_MAG]<0,3);//no mag, uncocked
		#### B 0 A_JumpIf(invoker.weaponstatus[MP40S_MAG]>=0,2);//Mag, cocked
		#### A 0;//no Mag, cocked
		#### # 0 A_SetCrosshair(21);
		#### # 1 {A_WeaponReady(WRF_ALL);
		            invoker.MAG_FORCEBOX=false;
		            //resets reload flags
		        }
		goto readyend;
	
	user3:
		#### # 0 A_MagManager("VirMP40Mag");
		goto ready;
		
	user2:
	firemode:
		usestock:
		#### # 3 A_WeaponBusy();
		#### # 0 A_JumpIf(invoker.weaponstatus[MP40D_STOCK]>0,"retractstock");
		#### # 1 offset(0,WEAPONTOP+1);
		#### # 1 offset(0,WEAPONTOP+2);
		#### # 1 offset(1,WEAPONTOP+4);
		#### # 1 A_StartSound("weapons/MACStockClick",CHAN_7);
		MP40 # 1 A_StockExtend();
//		#### # 0{invoker.weaponstatus[MP40D_STOCK]=1;}
		#### # 1 offset(2,WEAPONTOP+7);
		#### # 1 offset(1,WEAPONTOP+4);
		#### # 1 offset(0,WEAPONTOP+2);
		#### # 1 offset(0,WEAPONTOP+1);
		goto nope;
		retractstock:
		#### # 1 offset(0,WEAPONTOP+1);
		#### # 1 offset(0,WEAPONTOP+2);
		#### # 1 offset(1,WEAPONTOP+4);
		#### # 1 A_StockRetract();
//		#### # 0{invoker.weaponstatus[MP40D_STOCK]=0;}
		MP40 # 1 A_StartSound("weapons/MACStockClick",CHAN_7);
//		#### # 0{invoker.weaponstatus[MP40D_STOCK]=0;}
		#### # 1 offset(2,WEAPONTOP+7);
		#### # 1 offset(1,WEAPONTOP+4);
		#### # 1 offset(0,WEAPONTOP+2);
		#### # 1 offset(0,WEAPONTOP+1);
		goto nope;
		
	altfire:
  rackbolt:
	#### # 0 A_JumpIf(invoker.weaponstatus[MP40S_COCKED],"nope");
		#### # 2 offset(1,32);
		#### # 2 offset(2,42);
		MP40 B 0 A_JumpIf(invoker.weaponstatus[MP40S_MAG]>=0,2);//box mag, cocked
		#### A 0;//no mag, cocked
		#### # 2 offset(3,48){A_StartSound("MP40/Cock",8,CHANF_OVERLAP);
	      			            A_MuzzleClimb(frandom(0.2,0.24),-frandom(0.3,0.36),frandom(0.2,0.24),-frandom(0.3,0.36));
        
        			            //spawns an unspent round 
  			                  if(invoker.weaponstatus[MP40S_CHAMBER]==2)
  			                    A_SpawnItemEx("HDPistolAmmo",
					            		                 cos(pitch)*10,0,height*0.82-sin(pitch)*10,
					            		                 vel.x,vel.y,vel.z,
					            		                 0,SXF_ABSOLUTEMOMENTUM|SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH
				    			    		                );
				    			    		                
        			            //spawns an spent casing 
  			                  if(invoker.weaponstatus[MP40S_CHAMBER]==1)
  			                    A_SpawnItemEx("HDSpent9mm",
					            		                 cos(pitch)*10,0,height*0.82-sin(pitch)*10,
					            		                 vel.x,vel.y,vel.z,
					            		                 0,SXF_ABSOLUTEMOMENTUM|SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH
				    			    		                );
  			                    
						    			    //chamber empty, bolt cocked
					    			    	invoker.weaponstatus[MP40S_CHAMBER]=0;
					    			    	invoker.weaponstatus[MP40S_COCKED]=1;
					    			     }
		#### # 2 offset(2,42);	
		#### # 2 offset(1,32);
		goto readyend;
		
		//drop bolt without firing round
	dropbolt:
		#### E 0 A_JumpIf(invoker.weaponstatus[MP40S_MAG]>=0,2);
		#### D 0;
		#### # 1 offset(-1,36) A_StartSound("Mp40/Hit",CHAN_WEAPON,CHANF_OVERLAP);
		#### # 1 offset(1,30) A_StartSound("MP40/uncock",CHAN_WEAPON,CHANF_OVERLAP);
		goto readyend;
		
	althold:
	hold:
		goto nope;
	fire:
	  #### # 0 A_JumpIf(!invoker.weaponstatus[MP40S_COCKED]
	                    ,"nope");//do nothing if not cocked
	shoot:
	  #### # 0 {//drop the bolt
		    	    invoker.weaponstatus[MP40S_COCKED]=0;
		    	    
		    	    //abort if no magazine or ammo
		    	    if(invoker.weaponstatus[MP40S_MAG]<=0
		    	      )setweaponstate("dropbolt");
		    	   }
		#### E 0;
	  #### # 4 {
					if(!random(0,199))setweaponstate("dropbolt");
	    		    if(invoker.weaponstatus[MP40S_MAG]>0
	    		      ){invoker.weaponstatus[MP40S_MAG]--;
				          invoker.weaponstatus[MP40S_CHAMBER]=2;
		  	         }		    	  
		    	    // random chance of light primer strike
		          if(!random(0,299)
		            )setweaponstate("dropbolt");
	    	     }
		#### # 0 {if(invoker.weaponstatus[MP40S_CHAMBER]==2)
		            {A_GunFlash();
		             A_MuzzleClimb(-frandom(0.6,0.9),-frandom(0.8,1.1),
				                       frandom(0.4,0.5),frandom(0.6,0.8)
			                        );
		            }
		            
		          //random chance of failure to eject
		        /*  if(!random(0,99))
		            setweaponstate("dropbolt");*/
		         }
		#### B 0;         
		#### # 1 {//eject spent casing
		          if(invoker.weaponstatus[MP40S_CHAMBER]==1)
		      	    A_EjectCasing("HDSpent9mm",
		      	                   -frandom(166,170), //angle, -90 is standard
		      	                  (0,               //x axis velocity
		      	                   frandom(5,6),    //y axis velocity, positive is forward
		      	                   frandom(1,2)),   //z axis velocity, positive is upwards
		      	                  (17,-4,-5)          //spawn coordinates (z,x,y)
		      	                 );
	      		  
	      		  //chamber empty, bolt recocked
	      		  invoker.weaponstatus[MP40S_CHAMBER]=0;
	      		  invoker.weaponstatus[MP40S_COCKED]=1;
		         }
		#### # 1 {
		        	A_WeaponReady(WRF_NOFIRE);
	        		A_Refire("fire");
		}goto ready;
		
	flash:
		MP4F A 0 A_StartSound("mp40/shoot",CHAN_WEAPON);
		#### # 1 bright{HDFlashAlpha(64);
			              A_Light1();
			      			  let bbb=HDBulletActor.FireBullet(self,"HDB_9",spread:2.,speedfactor:frandom(0.99,1.05));
			    			    if(frandom(0,ceilingz-floorz)<bbb.speed*0.3
						          )A_AlertMonsters(200);
                    //round fired, spent casing in chamber
						        invoker.weaponstatus[MP40S_CHAMBER]=1;
						        A_ZoomRecoil(0.995);
			
						        A_MuzzleClimb(
						          -frandom(0.4,0.55),-frandom(0.8,1.0),
				        		  frandom(0.25,0.4),frandom(0.4,0.6)
						        );
	
			         		 }
		#### # 0 A_Light0();
		stop;
		
	unload:
		#### # 0{
			invoker.weaponstatus[0]|=MP40F_JUSTUNLOAD;
			if(invoker.weaponstatus[MP40S_MAG]>=0)setweaponstate("unmag");
		}goto nope;
		
	reload:
		#### # 0{
			invoker.weaponstatus[0]&=~MP40F_JUSTUNLOAD;
			bool nomag=HDMagAmmo.NothingLoaded(self,"VirMP40Mag");
			if(invoker.weaponstatus[MP40S_MAG]>=32)setweaponstate("nope");
			else if(invoker.weaponstatus[MP40S_MAG]<1 &&(pressinguse() || nomag));
			else if(nomag)setweaponstate("nope");
		}goto unmag;
	unmag:
		#### # 1 offset(0,34) A_SetCrosshair(21);
		#### # 2 offset(1,38);
		#### # 3 offset(2,42);
		#### # 4 offset(3,46) A_StartSound("weapons/rifleunload",8,CHANF_OVERLAP);
		#### # 0{
			int pmg=invoker.weaponstatus[MP40S_MAG];
			invoker.weaponstatus[MP40S_MAG]=-1;
			if(pmg<0)setweaponstate("magout");
			else if(
				(!PressingUnload()&&!PressingReload())
				||A_JumpIfInventory("VirMP40Mag",0,"null")
			){
				HDMagAmmo.SpawnMag(self,"VirMP40Mag",pmg);
				setweaponstate("magout");
			}
			else{
				HDMagAmmo.GiveMag(self,"VirMP40Mag",pmg);
				A_StartSound("weapons/pocket",9);
				setweaponstate("pocketmag");
			}
		}
	pocketmag:
		#### ### 5 offset(0,46) A_MuzzleClimb(frandom(-0.2,0.8),frandom(-0.2,0.4));
		goto magout;
	magout:
		#### # 0{
			if(invoker.weaponstatus[0]&MP40F_JUSTUNLOAD)setweaponstate("reloadend");
			else setweaponstate("loadmag");
		}

	loadmag:
		#### # 6 offset(0,46) A_MuzzleClimb(frandom(-0.2,0.8),frandom(-0.2,0.4));
		#### # 0 A_StartSound("weapons/pocket",9);
		#### # 5 offset(0,46) A_MuzzleClimb(frandom(-0.2,0.8),frandom(-0.2,0.4));
		#### # 4;
		#### # 0{
			let mmm=hdmagammo(findinventory("VirMP40Mag"));
			if(mmm){
				invoker.weaponstatus[MP40S_MAG]=mmm.TakeMag(true);
				A_StartSound("weapons/rifleload",8);
			}
		}
		goto reloadend;
		
	loadchamber:
		goto readyend;

	reloadend:
		#### # 2 offset(6,46);
		---- # 2 offset(4,40);
		---- # 2 offset(2,34);
		---- # 0 A_JumpIf(PressingReload()||PressingAltReload(),"nope");
		goto ready;
	
	spawn:
		
		MP4P ABCD -1 nodelay
		{
			if (invoker.weaponstatus[MP40S_MAG]>=0 && invoker.weaponstatus[MP40D_STOCK]>0)
			    frame = 3;
			else if (invoker.weaponstatus[MP40S_MAG]<0 && invoker.weaponstatus[MP40D_STOCK]>0)
				frame = 2;
			else if (invoker.weaponstatus[MP40S_MAG]>=0 && invoker.weaponstatus[MP40D_STOCK]==0)
				frame = 1;
			else frame = 0;
		}
		stop;
	}
	
	override void LoadoutConfigure(string input)
	{
		InitializeWepStats();
		if (GetLoadoutVar(input, "stock", 1) > 0) {
			weaponStatus[MP40D_STOCK]=1;
		}else {weaponStatus[MP40D_STOCK]=0;}
	}
	
	override void initializewepstats(bool idfa){
		weaponstatus[MP40S_MAG]=32;
		weaponstatus[MP40S_CHAMBER]=0;
		weaponstatus[MP40S_COCKED]=1;
//		weaponstatus[MP40D_STOCK]=0;
	}
}

enum mp40_status
{
	MP40F_JUSTUNLOAD=1,

	MP40D_STOCK=2,	//0 folded, 1 extended
	
	MP40S_FLAGS=0,
	MP40S_MAG=3,
	MP40S_CHAMBER=4, //0 empty, 1 spent, 2 loaded
	MP40S_COCKED=5,  //0 uncocked, 1 cocked
};


class VirMP40Mag:HD9mMag15{
	default{
		//$Category "Ammo/Hideous Destructor/"
		//$Title "PPSh-41 Box Magazine"
		//$Sprite "PSDMA0"
        scale 0.30;

		hdmagammo.maxperunit 32;
		hdmagammo.roundtype "HDPistolAmmo";
		hdmagammo.roundbulk ENC_9_LOADED;
		hdmagammo.magbulk ENC_MP40_BOX_EMPTY;
		tag "MP40 Magazine";
		inventory.pickupmessage "Picked up a MP40 magazine.";
		hdpickup.refid "MPM";
	}
	
	override string,string,name,double getmagsprite(int thismagamt)
	{
		string magsprite;
		if(thismagamt>0)
			magsprite = "MP4MA0";
		else
			magsprite = "MP4MC0";
		return magsprite,"PBRSA0","HDPistolAmmo",1;
	}
	override void GetItemsThatUseThis(){
		itemsthatusethis.push("VirMP40");
	}
	
	states{
	spawn:
		MP4M A -1;
		stop;
	spawnempty:
		MP4M D -1;
		stop;
	}
}

class VirMP40EmptyMag:IdleDummy{
	override void postbeginplay(){
		super.postbeginplay();
		HDMagAmmo.SpawnMag(self,"VirMP40Mag",0);
		destroy();
	}
}