version "4.14"

// Ammo
#include "zscript/Vir_Nails.zsc"
#include "zscript/Vir_CO2Nade.zsc"

// Weapons
#include "zscript/Vir_Satya.zsc"
#include "zscript/Vir_Vaswani.zsc"
#include "zscript/Vir_Nailgun.zsc"
#include "zscript/Vir_Nailpistol.zsc"
#include "zscript/Vir_Queen.zsc"
#include "zscript/Vir_Dumbo.zsc"
#include "zscript/Vir_Sabre.zsc"
#include "zscript/Vir_Cleaver.zsc"
#include "zscript/Vir_PipeWrench.zsc"

// Items
#include "zscript/Vir_Burnheal.zsc"
#include "zscript/Vir_ShieldBadge.zsc"
#include "zscript/Vir_BabuSpray.zsc"
#include "zscript/Vir_BatteryDynamo.zsc"

//----- Unfinished -----
//#include "zscript/Vir_Stingray.zsc"
//#include "zscript/Vir_E54Rifle.zsc"
//#include "zscript/Vir_Longbow.zsc"
//#include "zscript/Vir_YellowJacket.zsc"
//#include "zscript/Vir_Partisan.zsc"
//#include "zscript/Vir_TM25.zsc"
//#include "zscript/Vir_Scythe.zsc"
//#include "zscript/Vir_MP40.zsc"
//#include "zscript/Vir_Arrows.zsc"		//-----	Always enable with the Longbow!
